### ISSUE TITLE
Crashes on startup with a suboptimal swapchain image on linux

### ISSUE THREAD

**Issue by expenses** [GabeRundlett/gvox_engine#19]
Hi, thanks for making this open source! I tried to get it working on my slightly funky linux setup to not a lot of success. When running, I get a single frame of a mostly black screen and then `Aborted (core dumped)`. Here's the full callstack from GDB:

```
[[DAXA ASSERT FAILURE]]: error code: DAXA_RESULT_SUBOPTIMAL_KHR(1000001003), failed to acquire next swapchain image.

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid

Thread 1 "gvox_engine" received signal SIGABRT, Aborted.
0x00007ffff7899a9c in __pthread_kill_implementation ()
   from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7899a9c in __pthread_kill_implementation ()
   from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
#1  0x00007ffff7847576 in raise ()
   from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
#2  0x00007ffff782f935 in abort ()
   from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
#3  0x00007ffff7aacc2b in __gnu_cxx::__verbose_terminate_handler() [clone .cold] ()
   from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6
#4  0x00007ffff7abc20a in __cxxabiv1::__terminate(void (*)()) ()
   from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6
#5  0x00007ffff7abc275 in std::terminate() ()
   from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6
#6  0x00007ffff7abc4c7 in __cxa_throw ()
   from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6
#7  0x00007ffff7aaf39c in std::__throw_logic_error(char const*) ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6
#8  0x00007ffff7ae2480 in std::runtime_error::runtime_error(char const*) () from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6
#9  0x000000000063a488 in void check_result<1ul>(daxa_Result, char const*, std::array<daxa_Result, 1ul>) ()
#10 0x0000000000623c38 in daxa::Swapchain::acquire_next_image() ()
#11 0x00000000004d03a8 in VoxelApp::on_update (this=0x7fffffff7c90) at /home/ashley/projects/gvox2/src/voxel_app.cpp:102
#12 0x00000000004d0c1c in VoxelApp::run (this=this@entry=0x7fffffff7c90) at /home/ashley/projects/gvox2/src/voxel_app.cpp:92
#13 0x00000000004c3d54 in main () at /home/ashley/projects/gvox2/src/main.cpp:36
```

I'm on a laptop, running NixOS, a tiling window manager (Sway) in Wayland. Tiling window manager do some weird things on the first frame as they have to resize it to make it fit, so it's possible that some initial issues like that are causing things to not work. I'll try forcing the window to be floating.

As an aside, the build process with vcpkg on NixOS is pretty rough as the two don't play super nice. I'll try and come up with a build script that's a bit nicer and might make a PR for that.

**Comment by GabeRundlett** [comment]
The issue here is something to do with WSI. It is specifically a Linux/your driver thing that I have no way of testing
